export const getTournament = async (id: string) => {
  return (await getTournaments()).find((tournament) => tournament.id.toString() === id)!
}

export const getRecentTournaments = async () => {
  return (await getTournaments()).slice(0, 10)
}

export const getTournaments = async () => {
  return [
    {
      id: 1000,
      name: 'Summer League Championship',
      url: '/tournaments/1000',
      startDate: 'Aug 15, 2024',
      endDate: 'Aug 30, 2024',
      status: 'Active',
      teams: 32,
      maxTeams: 32,
      organizer: 'Elite Sports League',
      location: 'Central Sports Complex',
      registrationFee: 150,
      prizePool: '$10,000',
      sport: 'Basketball',
    },
    {
      id: 1001,
      name: 'Winter Volleyball Open',
      url: '/tournaments/1001',
      startDate: 'Sep 5, 2024',
      endDate: 'Sep 20, 2024',
      status: 'Upcoming',
      teams: 16,
      maxTeams: 24,
      organizer: 'Volleyball Pro League',
      location: 'Metro Arena',
      registrationFee: 100,
      prizePool: '$5,000',
      sport: 'Volleyball',
    },
    {
      id: 1002,
      name: 'Regional Soccer Cup',
      url: '/tournaments/1002',
      startDate: 'Oct 1, 2024',
      endDate: 'Oct 15, 2024',
      status: 'Upcoming',
      teams: 8,
      maxTeams: 16,
      organizer: 'City Soccer Association',
      location: 'Municipal Stadium',
      registrationFee: 200,
      prizePool: '$8,000',
      sport: 'Soccer',
    },
    {
      id: 1003,
      name: 'Spring Tennis Championship',
      url: '/tournaments/1003',
      startDate: 'Jul 10, 2024',
      endDate: 'Jul 25, 2024',
      status: 'Completed',
      teams: 24,
      maxTeams: 24,
      organizer: 'Tennis Masters Club',
      location: 'Grand Tennis Center',
      registrationFee: 75,
      prizePool: '$3,500',
      sport: 'Tennis',
    },
    {
      id: 1004,
      name: 'Annual Cricket League',
      url: '/tournaments/1004',
      startDate: 'Sep 12, 2024',
      endDate: 'Sep 28, 2024',
      status: 'Upcoming',
      teams: 12,
      maxTeams: 16,
      organizer: 'Cricket Federation',
      location: 'Sports Ground Complex',
      registrationFee: 180,
      prizePool: '$6,500',
      sport: 'Cricket',
    },
    {
      id: 1005,
      name: 'Youth Basketball Tournament',
      url: '/tournaments/1005',
      startDate: 'Aug 20, 2024',
      endDate: 'Aug 22, 2024',
      status: 'Active',
      teams: 16,
      maxTeams: 16,
      organizer: 'Youth Sports Academy',
      location: 'Community Center',
      registrationFee: 50,
      prizePool: '$1,500',
      sport: 'Basketball',
    },
    {
      id: 1006,
      name: 'Corporate Badminton Cup',
      url: '/tournaments/1006',
      startDate: 'Jun 30, 2024',
      endDate: 'Jul 5, 2024',
      status: 'Completed',
      teams: 20,
      maxTeams: 20,
      organizer: 'Corporate Sports Club',
      location: 'Executive Sports Center',
      registrationFee: 120,
      prizePool: '$4,000',
      sport: 'Badminton',
    },
    {
      id: 1007,
      name: 'Beach Volleyball Championship',
      url: '/tournaments/1007',
      startDate: 'Oct 8, 2024',
      endDate: 'Oct 10, 2024',
      status: 'Upcoming',
      teams: 12,
      maxTeams: 20,
      organizer: 'Coastal Sports League',
      location: 'Seaside Beach Courts',
      registrationFee: 80,
      prizePool: '$2,500',
      sport: 'Beach Volleyball',
    },
    {
      id: 1008,
      name: 'Indoor Football League',
      url: '/tournaments/1008',
      startDate: 'Nov 1, 2024',
      endDate: 'Nov 20, 2024',
      status: 'Upcoming',
      teams: 8,
      maxTeams: 12,
      organizer: 'Indoor Sports Federation',
      location: 'Indoor Arena Complex',
      registrationFee: 250,
      prizePool: '$12,000',
      sport: 'Indoor Football',
    },
    {
      id: 1009,
      name: 'Table Tennis Open',
      url: '/tournaments/1009',
      startDate: 'Jul 15, 2024',
      endDate: 'Jul 18, 2024',
      status: 'Completed',
      teams: 32,
      maxTeams: 32,
      organizer: 'Table Tennis Association',
      location: 'Sports Recreation Center',
      registrationFee: 40,
      prizePool: '$1,200',
      sport: 'Table Tennis',
    },
  ]
}

export const getOrganizers = async () => {
  return [
    {
      id: 1,
      name: 'Elite Sports League',
      email: 'info@elitesports.com',
      tournaments: 5,
      rating: 4.8,
    },
    {
      id: 2,
      name: 'Volleyball Pro League',
      email: 'contact@volleyballpro.com',
      tournaments: 3,
      rating: 4.6,
    },
    {
      id: 3,
      name: 'City Soccer Association',
      email: 'admin@citysoccer.org',
      tournaments: 8,
      rating: 4.7,
    },
    {
      id: 4,
      name: 'Tennis Masters Club',
      email: 'hello@tennismasters.com',
      tournaments: 4,
      rating: 4.9,
    },
  ]
}